### ISSUE TITLE
STM32G031K8

### ISSUE THREAD

**Issue by isnadh** [maxgerhardt/pio-stm32g031c8-support#1]
Could you kindly make for STM32G031K8 nucleo board. Thanks

**Comment by maxgerhardt** [comment]
Added in b55a23b1e2821fe73117c3c2d4f97f6cd1b0d3df. 

I do not have a Nucleo G031K8 board to test it, so feedback is appreciated. 

I did the pinmap for the Arduino header as per [the schematics](https://www.st.com/content/ccc/resource/technical/layouts_and_diagrams/schematic_pack/group1/05/c3/27/2a/6b/db/41/f1/MB1455-G031K8-C01_Schematic/files/MB1455-G031K8-C01_Schematic.pdf/jcr:content/translations/en.MB1455-G031K8-C01_Schematic.pdf) on [the main documentation site](https://www.st.com/en/evaluation-tools/nucleo-g031k8.html#documentation). So, the Serial output and LED and button should work automatically.

When you clone the project the `platformio.ini` is automatically set up for the Nucleo G031K8 and a Serial + blinky sketch.

Please let me know if this works.

**Comment by maxgerhardt** [comment]
Any update?

**Comment by maxgerhardt** [comment]
Closing since no response received and support added. If there's an issue with the implementation, open another issue.
